---
- name: Basic connectivity and system info
  hosts: pis
  become: false
  gather_facts: true

  tasks:
    - name: Show hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Show OS
      ansible.builtin.debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
